export const LOADING_DESIGNS = 'LOADING_DESIGNS'
export const GET_DESIGNS_ERROR = 'GET_DESIGNS_ERROR'
export const GET_DESIGNS_SUCCESS = 'GET_DESIGNS_SUCCESS'

export const LOADING_PORTFOLIO = 'LOADING_PORTFOLIO'
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR'
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS'


export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

export const LOADING_SINGLE_PRODUCT = 'LOADING_SINGLE_PRODUCT'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'

export const SET_GRID_VIEW = 'SET_GRID_VIEW'

export const FILTERS_PRODUCTS = 'FILTERS_PRODUCTS'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'